### ISSUE TITLE
Version 1.6 is out

### ISSUE THREAD

**Issue by davidedg** [ParrotSec/hexinject#4]
Hi,

this repo seems outdated - http://hexinject.sourceforge.net/ is at version 1.6

Also, in version 1.6, there's a compilation error for debian/ubuntu
this can be resolved using this Makefile:

CC = gcc
CFLAGS = -Wall
LDFLAGS = -lpcap

all:
        $(CC) $(CFLAGS) -o hexinject hexinject.c $(LDFLAGS)
        $(CC) $(CFLAGS) -o prettypacket prettypacket.c $(LDFLAGS)
        $(CC) $(CFLAGS) -o hex2raw hex2raw.c $(LDFLAGS)

clean:
        rm -f hexinject prettypacket hex2raw *~

**Comment by PalinuroSec** [comment]
don't worry, the parrot repository already provides the latest 1.6 version

we took it from the kali/debian repos and we will update this git repo only if we need to apply custom patches
